### ISSUE TITLE
Repository roadmap

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/peculiar-react-components#64]
Monorepo organization - [lerna](https://github.com/lerna/lerna)
CI - [GitHub Action](https://github.com/features/actions) or [Circle CI](https://circleci.com/)
Main language - [Typescript](https://www.typescriptlang.org/)
Components styling - [Scss](https://sass-lang.com/guide) and [CSS Variables](https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties)
Components preview - [Storybook](https://storybook.js.org/)
Testing - [Karma](http://karma-runner.github.io/latest/index.html)
Components testing utility - [Enzyme](https://enzymejs.github.io/enzyme/)
Lint - [ESLint](https://eslint.org/)
Stylelint- [StyleLint](https://stylelint.io/)
WebApp runner - [Webpack](https://webpack.js.org/)
...

Packages:
- [ ]  `@peculiar/react-components`
- [ ]  `@peculiar/ui-utils`
- [ ]  `@peculiar/ui-theming`
- [ ]  `@peculiar/webpack-scripts`
- [ ]  `@peculiar/i18n`
- [ ]  `@peculiar/react-i18n`
- [ ]  `@peculiar/karma-scripts`
- [ ]  `@peculiar/enzyme-utilities`
- [ ]  `@peculiar/eslint-config`
- [ ]  `@peculiar/stylelint-config`
...

Basic package structure:
```
@peculiar/package_name
  - dist (out)
  - src
    - index.ts
    - name
      - name.ts
      - name.spec.ts
      - index.ts
  - package.json
  - README.md
  - tsconfig.json
```

New structure created on the [branch](https://github.com/PeculiarVentures/react-components/tree/new-structure)
